kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: nginx-httproute
  namespace: kong-test2-app1
  annotations:
    konghq.com/strip-path: 'true'
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: kong
      namespace: kong-common-gateway-2
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /test-app-1
      backendRefs:
        - name: nginx
          port: 80

