apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: kong-common-gateway-test-app-2-grant
  namespace: kong-test-app-2
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: kong-common-gateway
  to:
  - group: ""
    kind: Service
